### ISSUE TITLE
INFOGRAFÍA DE LIBRERIAS

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/infografia-de-las-librerias-Eva155#2]
[INFOGRAFÍA DE LIBRERÍAS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Eva155/files/6301363/INFOGRAFIA.DE.LIBRERIAS.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20

Calificó: Israel Nicolás, Uzías López

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
